name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3.0.10
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn --batch-mode package

#       - name: Publish Test Report
#         uses: scacap/action-surefire-report@v1.0.12
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Analyze with SonarCloud
        continue-on-error: true
        run: mvn --batch-mode sonar:sonar -Dsonar.organization=jfisbein-github -Dsonar.projectKey=jfisbein_java-rate-limit -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
