name: Release

# Run workflow on tags to the `master` branch
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Release Maven package
        uses: WasiqB/maven-publish-action@v2.7.0
        with:
          maven_args: --batch-mode
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          server_username: ${{ secrets.nexus_username }}
          server_password: ${{ secrets.nexus_password }}
