name: Release

# Run workflow on tags to the `master` branch
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          
      - name: Create settings.xml file
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          servers: >
            [
              {
                "id": "central",
                "username": "${env.SONATYPE_CENTRAL_USERNAME}",
                "password": "${env.SONATYPE_CENTRAL_PASSWORD}"
              }
            ]

      - name: Publish package
        run: mvn --batch-mode -P deploy deploy
